### PR TITLE
Rendering elements Page Translation

### PR DESCRIPTION
**Pull request by madhusudhan1234**
- [x] Rendering elements page translation to nepali

### CODE REVIEW

**Comment by samundrak** [comment]
Thanks hai madhu for carrying it on :)

**Comment by madhusudhan1234** [comment]
> Thanks hai madhu for carrying it on :)

You're welcome @samundrak! I am expecting some suggestions from you if we can make more simple translation in Nepali.

**Comment by madhusudhan1234** [comment]
@samundrak Please review this PR

**Comment by samundrak** [comment]
Thik cha madhu

**Pull request merged**
